repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.3.5
    hooks:
      - id: sqlfluff-lint
        args: [--dialect=postgres, --templater=dbt]
        additional_dependencies: ['dbt-postgres', 'sqlfluff-templater-dbt']
        files: \.(sql)$
        exclude: target/

      - id: sqlfluff-fix
        args: [--dialect=postgres, --templater=dbt]
        additional_dependencies: ['dbt-postgres', 'sqlfluff-templater-dbt']
        files: \.(sql)$
        exclude: target/
        stages: [manual]

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        files: \.py$

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        files: \.py$