version: 2

models:
  - name: stg_customers
    description: "Cleaned and standardized customer data"
    columns:
      - name: customer_id
        description: "Unique identifier for customers"
        tests:
          - unique
          - not_null
      - name: email_lower
        description: "Customer email in lowercase"
        tests:
          - not_null
          - unique
      - name: full_name
        description: "Customer full name"
        tests:
          - not_null

  - name: stg_orders
    description: "Cleaned and standardized order data"
    columns:
      - name: order_id
        description: "Unique identifier for orders"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key to customers"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_customers')
                field: customer_id
      - name: total_amount
        description: "Order total amount"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: true